# Generated by Django 4.2 on 2024-03-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("dirty", "Dirty"),
                            ("maintenance", "Needs Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("progress_description", models.TextField(blank=True, null=True)),
                ("inventory_update", models.TextField(blank=True, null=True)),
                (
                    "room_image",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
