# Generated by Django 5.0.1 on 2024-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotelmanage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomstatus",
            name="room_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="room_images/<django.db.models.fields.CharField>",
            ),
        ),
    ]
