# Generated by Django 5.0.1 on 2024-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotelmanage", "0002_alter_roomstatus_room_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomstatus",
            name="flagged_for_maintenance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="roomstatus",
            name="status",
            field=models.CharField(
                choices=[("clean", "Clean"), ("maintenance", "Needs Maintenance")],
                max_length=20,
            ),
        ),
    ]
