# Generated by Django 5.0.1 on 2024-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotelmanage", "0003_roomstatus_flagged_for_maintenance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomstatus",
            name="inventory_update",
        ),
        migrations.AddField(
            model_name="roomstatus",
            name="is_cleaned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomstatus",
            name="minibar_items",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roomstatus",
            name="toiletries",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roomstatus",
            name="towels",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roomstatus",
            name="room_image",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
    ]
